// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plenumio.Infrastructure.Data;

#nullable disable

namespace Plenumio.Infrastructure.Migrations
{
    [DbContext(typeof(PlenumioDbContext))]
    [Migration("20250820193130_postTableAndPostTagTable")]
    partial class postTableAndPostTagTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Plenumio.Core.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PrivacyType")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Plenumio.Core.Entities.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("Plenumio.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6379), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayedName = "Technology",
                            IsDeleted = false,
                            Name = "technology",
                            Type = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6380), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6384), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayedName = "Life",
                            IsDeleted = false,
                            Name = "life",
                            Type = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6384), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6387), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayedName = "Science",
                            IsDeleted = false,
                            Name = "science",
                            Type = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6388), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6390), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayedName = "Art",
                            IsDeleted = false,
                            Name = "art",
                            Type = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6391), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6394), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayedName = "Gaming",
                            IsDeleted = false,
                            Name = "gaming",
                            Type = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 8, 20, 19, 31, 29, 281, DateTimeKind.Unspecified).AddTicks(6394), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Plenumio.Core.Entities.PostTag", b =>
                {
                    b.HasOne("Plenumio.Core.Entities.Post", "Post")
                        .WithMany("PostTag")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plenumio.Core.Entities.Tag", "Tag")
                        .WithMany("PostTag")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Plenumio.Core.Entities.Tag", b =>
                {
                    b.HasOne("Plenumio.Core.Entities.Tag", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Plenumio.Core.Entities.Post", b =>
                {
                    b.Navigation("PostTag");
                });

            modelBuilder.Entity("Plenumio.Core.Entities.Tag", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("PostTag");
                });
#pragma warning restore 612, 618
        }
    }
}
